Algeria:
  backer: Julie
  status: In
Argentina:
  backer: Sumika
  status: In
Australia:
  backer: Phil
  status: Out
Belgium:
  backer: Carlina
  status: In
Bosnia and Herzegovina:
  backer: Carl
  status: Out
Brazil:
  backer: Andrea
  status: In
Cameroon:
  backer: Amanda
  status: Out
Chile:
  backer: Ali
  status: Out
Colombia:
  backer: Carlina
  status: In
Costa Rica:
  backer: Ulrich
  status: In
Croatia:
  backer: Stuart H
  status: Out
Ecuador:
  backer: Tom
  status: Out
England:
  backer: Marisa
  status: Out
France:
  backer: Michelle
  status: In
Germany:
  backer: Anneza
  status: In
Ghana:
  backer: Iraia
  status: Out
Greece:
  backer: Samantha
  status: Out
Honduras:
  backer: Andrea
  status: Out
Iran:
  backer: James
  status: Out
Italy:
  backer: Kass
  status: Out
Ivory Coast:
  backer: Elpida
  status: Out
Japan:
  backer: Gavin B
  status: Out
Mexico:
  backer: Liz
  status: Out
Netherlands:
  backer: Amanda
  status: In
Nigeria:
  backer: Richard
  status: In
Portugal:
  backer: Clara
  status: Out
Russia:
  backer: Sam P
  status: Out
South Korea:
  backer: Emma
  status: Out
Spain:
  backer: Jade
  status: Out
Switzerland:
  backer: Briony
  status: In
United States:
  backer: Georgia
  status: In
Uruguay:
  backer: Jeni
  status: Out
